final Map<String, String> countryImages = {
  "Algeria": "assets/images/algeria_image.jpeg",
  "Angola": "assets/images/angola_image.jpg",
  "Benin": "assets/images/benin_image.jpg",
  "Botswana": "assets/images/botswana_image.jpeg",
  "Burkina Faso": "assets/images/burkina_faso_image.jpeg",
  "Cabo Verde": "assets/images/cape_verde_image.jpg",
  "Cameroon": "assets/images/cameroon_image.jpg",
  "Central African Republic": "assets/images/central_african_republic_image.jpg",
  "Chad": "assets/images/chad_image.jpeg",
  "Comoros": "assets/images/comoros_image.jpg",
  "Congo": "assets/images/congo_image.jpg",
  "Côte d'Ivoire": "assets/images/cote_d'ivoire_image.jpeg",
  "Djibouti": "assets/images/djibouti_image.jpg",
  "Egypt": "assets/images/egypt_image.png",
  "Equatorial Guinea": "assets/images/equatorial_guinea.jpg",
  "Eritrea": "assets/images/eritrea_image.jpg",
  "Eswatini": "assets/images/eswatini_image.jpeg",
  "Ethiopia": "assets/images/ethiopia_image.jpeg",
  "Gabon": "assets/images/gabon_image.jpeg",
  "Gambia": "assets/images/gambia_image.jpg",
  "Ghana": "assets/images/ghana_image.jpg",
  "Guinea": "assets/images/guinea_image.jpg",
  "Guinea-Bissau": "assets/images/guinea_bissau_image.jpg",
  "Ivory Coast": "assets/images/cote_d'ivoire_image.jpeg",
  "Kenya": "assets/images/kenya_image.jpg",
  "Lesotho": "assets/images/lesotho_image.jpg",
  "Liberia": "assets/images/liberia_image.jpg",
  "Libya": "assets/images/libya_image.jpg",
  "Madagascar": "assets/images/madagascar_image.jpg",
  "Malawi": "assets/images/malawi_image.jpg",
  "Mali": "assets/images/mali_image.jpg",
  "Mauritania": "assets/images/mauritania_image.jpg",
  "Mauritius": "assets/images/mauritius_image.jpeg",
  "Morocco": "assets/images/morocco_image.jpeg",
  "Mozambique": "assets/images/mozambique_image.jpg",
  "Namibia": "assets/images/namibia_image.jpeg",
  "Niger": "assets/images/niger_image.jpg",
  "Nigeria": "assets/images/lagos_image.jpg",
  'Reunion': 'assets/images/reunion_image.jpg',
  "Rwanda": "assets/images/rwanda_image.jpg",
  'Saint Helena, Ascension and Tristan da Cunha': 'assets/images/saint_helena_image.webp',
  "São Tomé and Príncipe": "assets/images/sao_tome_image.jpeg",
  "Senegal": "assets/images/senegal_image.jpg",
  "Seychelles": "assets/images/seychelles_image.jpeg",
  "Sierra Leone": "assets/images/sierra_leone_image.jpg",
  "Somalia": "assets/images/somalia_image.jpeg",
  "South Africa": "assets/images/south_africa_image.jpeg",
  "South Sudan": "assets/images/south_sudan_image.jpeg",
  "Sudan": "assets/images/south_sudan_image.jpeg",
  "Tanzania": "assets/images/tanzania_image.jpg",
  "Togo": "assets/images/togo_image.jpg",
  "Tunisia": "assets/images/tunisia_image.jpeg",
  "Uganda": "assets/images/uganda_image.jpeg",
  'Western Sahara': 'assets/images/western_sahara_image.jpeg',
  "Zambia": "assets/images/zambia_image.jpeg",
  "Zimbabwe": "assets/images/zimbabwe_image.jpeg",
};