final List<String> africanFacts = [
  "Africa is the second-largest continent on Earth, after Asia.",
  "The Sahara Desert in Africa is the largest hot desert in the world.",
  "The Nile River in Africa is the longest river in the world.",
  "Africa is home to 54 recognized countries.",
  "Nigeria has the largest population in Africa.",
  "Mount Kilimanjaro in Tanzania is the highest point in Africa.",
  "Africa’s lowest point is Lake Assal in Djibouti.",
  "Madagascar is the fourth-largest island in the world.",
  "Africa is surrounded by the Mediterranean Sea, Red Sea, Indian Ocean, and Atlantic Ocean.",
  "The continent straddles both the Northern and Southern Hemispheres.",
  "Cairo, Egypt, is the largest city in Africa by population.",
  "Africa is often called the cradle of humankind because the earliest fossils of humans were found there.",
  "South Africa has 11 official languages.",
  "Lake Victoria, located between Uganda, Kenya, and Tanzania, is the largest lake in Africa.",
  "The Sahara Desert is roughly the same size as the United States.",
  "The Great Rift Valley runs through eastern Africa and is visible from space.",
  "Africa is home to the world’s largest wildlife migration — the Great Wildebeest Migration in Kenya and Tanzania.",
  "Africa’s population is over 1.4 billion people and growing rapidly.",
  "The continent is rich in natural resources, including gold, diamonds, and oil.",
  "Ethiopia is one of the few African countries never colonized by Europe.",
  "Africa has over 1,500 distinct languages.",
  "The continent covers about 20% of Earth’s total land area.",
  "The world’s largest waterfall by volume, Inga Falls, is in the Democratic Republic of Congo.",
  "The Victoria Falls, shared by Zambia and Zimbabwe, is one of the Seven Natural Wonders of the World.",
  "Africa’s youngest country is South Sudan, established in 2011.",
  "The equator runs through seven African countries.",
  "Botswana is home to one of the world’s largest salt flats, the Makgadikgadi Pan.",
  "Africa’s largest country by land area is Algeria.",
  "The smallest country in Africa is Seychelles.",
  "Kenya is known as the cradle of humankind due to its archaeological discoveries.",
  "The Sahara Desert expands southward by about 30 miles each year due to desertification.",
  "The Congo Rainforest is the second largest tropical rainforest after the Amazon.",
  "The African continent experiences some of the highest average temperatures on Earth.",
  "Africa’s Great Lakes region contains 25% of the planet’s freshwater.",
  "Morocco is famous for its blue city, Chefchaouen.",
  "The Baobab tree, found across Africa, can live for over 2,000 years.",
  "Africa has more than 3,000 ethnic groups.",
  "Egypt’s pyramids are over 4,000 years old and among the world’s most iconic landmarks.",
  "The Serengeti National Park in Tanzania hosts millions of migrating animals annually.",
  "Lake Tanganyika is the world’s longest freshwater lake.",
  "The African elephant is the largest land animal on Earth.",
  "Africa’s internet usage is growing faster than any other region in the world.",
  "The currency with the highest value in Africa is the Libyan Dinar.",
  "Africa’s oldest university is the University of Al Quaraouiyine in Morocco, founded in 859 AD.",
  "Cape Town, South Africa, was the first city in Africa to host the FIFA World Cup in 2010.",
  "Africa has 16 landlocked countries.",
  "Mauritius is one of the most peaceful countries in Africa.",
  "The Sahara used to be a lush, green region thousands of years ago.",
  "The Okavango Delta in Botswana is one of the world’s largest inland deltas.",
  "Africa is the only continent that stretches from the northern temperate zone to the southern temperate zone."
];